language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - DB=sqlite3
before_script:
  - RAILS_ENV=test bundle exec rake --trace db:create db:schema:load
script:
  - RAILS_ENV=test bundle exec rake --trace test
bundler_args: "--without development assets"